module.exports = [
  {
    company: 'Cooltra',
    url: 'https://www.cooltra.com',
    logo: '/public/logos/cooltra.png',
    startDate: 'Jun 2021',
    endDate: 'till now',
    items: [
      'Designing and creating design components in figma',
      'Building a monorepo consisting of frontend libraries',
    ],
    stack: [
      'Typescript',
      'React',
      'React Query',
      'Tailwind CSS',
      'Cypress',
      'Figma',
    ],
  },
  {
    company: 'Docplanner',
    url: 'https://www.docplanner.com',
    logo: '/public/logos/docplanner.jpeg',
    startDate: 'Sep 2020',
    endDate: 'June 2021',
    items: [
      `Creating a tablet version of the doctor's app`,
      `Building a profile screen in the patient's app`,
      'Building a mobile UI kit from scratch',
    ],
    stack: ['Typescript', 'React', 'React Native', 'GraphQL', 'Jest'],
  },
  {
    company: 'Zopa',
    url: 'https://www.zopa.com',
    logo: '/public/logos/zopa.jpeg',
    startDate: 'Aug 2018',
    endDate: 'Aug 2020',
    items: [
      'Developing credit card web origination journey',
      'Building credit card module for the React Native app',
      'Heavily contributing to Zopa open source components library',
    ],
    stack: ['Typescript', 'React', 'React Native', 'Redux', 'Jest', 'Cypress'],
  },
  {
    company: 'Strands',
    url: 'https://www.strands.com',
    logo: '/public/logos/strands.jpeg',
    startDate: 'May 2017',
    endDate: 'Aug 2018',
    items: [
      'Architecting components library used in all Strands products',
      'Implementing brand new invoicing widget',
    ],
    stack: ['React', 'Redux', 'Immutable'],
  },
  {
    company: 'Whisbi',
    url: 'https://www.whisbi.com',
    logo: '/public/logos/whisbi.png',
    startDate: 'Mar 2016',
    endDate: 'Apr 2017',
    items: [
      'Redesigning and maintaining of clients’ landing pages',
      'Improving company Wordpress website',
    ],
    stack: ['jQuery', 'Sass', 'Handlebars', 'Gulp'],
  },
];
